let ShowDataItems = [{
    id: "firstitem",
    discount: "-14%",
    img: "assests/media/photos/iphone6.png",
    productDes: "Phone, Accesories",
    productname: "Iphone",
    desc: "Aliquam dignissim sem nisl, vel the indust",
    price: 1000,
    
},
{
    id: "seconditem",
    discount: "-13%",
    img: "assests/media/photos/ipad.png",
    productDes: "Phone, Accesories",
    productname: "Ipad",
    desc: "Aliquam dignissim sem nisl, vel the indust",
    price: 1200,  
},
{
    id: "thirditem",
    discount: "-15%",
    img: "assests/media/photos/bag.png",
    productDes: "Bag, Accesories",
    productname: "Awesome Bag",
    desc: "Aliquam dignissim sem nisl, vel the indust",
    price: 200,
},
{
    id: "fourthitem",
    discount: "-24%",
    img: "assests/media/photos/vr.png",
    productDes: "VR, Accesories",
    productname: "VR Set",
    desc: "LAliquam dignissim sem nisl, vel the indust",
    price: 500,
},
{
    id: "fifthitem",
    discount: "-54%",
    img: "assests/media/photos/tv.png",
    productDes: "Tv, Accesories",
    productname: "Big Tv",
    desc: "Aliquam dignissim sem nisl, vel the indust",
    price: 1200,
},
{
    id: "sixthitem",
    discount: "-24%",
    img: "assests/media/photos/psconsole.png",
    productDes: "Console, Accesories",
    productname: "PS Console",
    desc: "Aliquam dignissim sem nisl, vel the indust",
    price: 300,
},
{
    id: "seventhitem",
    discount: "-34%",
    img: "assests/media/photos/headphones2.png",
    productDes: "Headphone, Accesories",
    productname: "Headphones",
    desc: "Aliquam dignissim sem nisl, vel the indust",
    price: 600,
},
{
    id: "eighthitem",
    discount: "-64%",
    img: "assests/media/photos/headphones.png",
    productDes: "Headphone, Accesories",
    productname: "Headphones",
    desc: "Aliquam dignissim sem nisl, vel the indust",
    price: 400,
},
{
    id: "ninthitem",
    discount: "-74%",
    img: "assests/media/photos/bigspeaker.png",
    productDes: "Speaker, Accesories",
    productname: "Big Speaker",
    desc: "Aliquam dignissim sem nisl, vel the indust",
    price: 1900,
},
{
    id: "tenthitem",
    discount: "-44%",
    img: "assests/media/photos/consolw-red.png",
    productDes: "Console, Accesories",
    productname: "Console",
    desc: "Aliquam dignissim sem nisl, vel the indust",
    price: 400,
},];